export const English = {
  language: 'English',
  home: 'Home',
  schedule: 'Schedule',
  channels: 'Channels',
  notifications: 'Notifications',
  more: 'More',
  manageShift: 'Manage Shifts',
  firstContact: 'First Contact',
  firstContactMsg: 'We want to hear you!!',
  suggestionBox: 'Suggestion Box',
  mantSuggestionBox: 'Maintenance Suggestion Box',
  survey: 'Survey',
  nextShift: 'Next Shift!!',
  personalInformation: 'Personal Information',
  myBenefits: 'My Benefits',
  trainingCenter: 'Training Center',
  badges: 'Badges',
  changeLanguage: 'Change Language',
  humanResources: 'Human Resources',
  diversityAndInclusion: 'Diversity and Inclision',
  COVID19Comunications: 'COVIT-19 Comunications',
  FocusOnWellness: 'Focus On Wellness',
  StayingSafeAtHome: 'Staying Safety at Home',
  FeedYourSpirit: 'Feed Your Spirit',
  NewsToKnow: 'News To Know',
  TheScoop: 'The Scoop',
  CarrierCorner: 'Carrier Corner',
  FAQs: 'FAQs',
  Warehouse: 'Warehouse',
  Announcements: 'Announcements',
  Celebrations: 'Celebrations',
  AssociateResorce: 'Associate Resorce',
  BRIAnnouncements: 'BRI Announcements',
  SafetyChannel: 'Safety Channel',
  TheHumanSpirit: 'The Human Spirit',
  PoliciesAndProcedures: 'Policies And Procedures',
  PromotionsAndRollesChanges: 'Promotions And Rolles Changes',
  WelcomeNewHires: 'Welcome New Hires',
  Deparment: 'Deparment',
  FirstShiftFreezer: 'First Shift Freezer',
  FirstShiftPerishable: 'First Shift Perishable',
  SecondShiftFreezer: 'Second Shift Freezer',
  SecondShiftPrerishable: 'Second Shift Prerishable',
  Sanitation: 'Sanitation'
};

  
export const Spanish = {
  language: 'Spanish',
  home: 'Inicio',
  schedule: 'Horario',
  channels: 'Canales',
  notifications: 'Notificaciones',
  more: 'Mas',
  manageShift: 'Gestionar Turnos',
  firstContact: 'Primer Contacto',
  firstContactMsg: 'Queremos escucharte!!',
  suggestionBox: 'Caja de Sugerencias',
  mantSuggestionBox: 'Caja de Sugerencias de Mantenimiento',
  survey: 'Encuestas',
  nextShift: 'Siguiente Turno !!!',
  personalInformation: 'Informacion Personal',
  myBenefits: 'Mis Beneficios',
  trainingCenter: 'Centro de Entrenamiento',
  badges: 'Insignias',
  changeLanguage: 'Cambiar Idioma',
  humanResources: 'Recursos Humanos',
  diversityAndInclusion: 'Diversidad e Inclusión',
  COVID19Comunications: 'COVIT-19 Comunicados',
  FocusOnWellness: 'Focus en Bienestar',
  StayingSafeAtHome: 'Estar Seguro en Casa',
  FeedYourSpirit: 'Alimenta el Espirito',
  NewsToKnow: 'Noticias',
  TheScoop: 'Un Espacio',
  CarrierCorner: 'La Esquina de la Carrera',
  FAQs: 'Hechos',
  Warehouse: 'Bodega',
  Announcements: 'Anuncios',
  Celebrations: 'Celebraciones',
  AssociateResorce: 'Recursos de los Asociados',
  BRIAnnouncements: 'BRI Anuncios',
  SafetyChannel: 'Canal de Seguridad',
  TheHumanSpirit: 'El Espiritu Humano',
  PoliciesAndProcedures: 'Polizas y Procedimientos',
  PromotionsAndRollesChanges: 'Promociones y Camios en Roles',
  WelcomeNewHires: 'Bienvenida a Nuevos Asociados',
  Deparment: 'Departamentos',
  FirstShiftFreezer: 'Primer Turno Congelador',
  FirstShiftPerishable: 'Primer Turno Perecederos',
  SecondShiftFreezer: 'Segundo Turno Congelador',
  SecondShiftPrerishable: 'Segundo Turno Perecederos',
  Sanitation: 'Limpieza'

};

export const Italian = {
  language: 'Italian',
  home: 'Inizio',
  schedule: 'Orario',
  channels: 'Canali',
  notifications: 'Notifiche',
  more: 'Di Più',
  manageShift: 'Gestisci Turni',
  firstContact: 'Primo Contatto',
  firstContactMsg: 'Vogliamo sentirti!!',
  suggestionBox: 'Scatola dei Suggerimenti',
  mantSuggestionBox: 'Scatola dei Suggerimenti per la Manutenzione',
  survey: 'Indagine',
  nextShift: 'Prossimo Turno!!!',
  personalInformation: 'Informazione Personale',
  myBenefits: 'I Miei Vantaggi',
  trainingCenter: 'Centro di Addestramento',
  badges: 'Distintivi',
  changeLanguage: 'Cambia Lingua',
  humanResources: 'Risorse Umano',
  diversityAndInclusion: 'Diversità e Inclusione',
  COVID19Comunications: 'COVIT-19 Comunicazioni',
  FocusOnWellness: 'Focus sul Benessere',
  StayingSafeAtHome: 'Rimanere al Sicuro a Casa',
  FeedYourSpirit: 'Nutri il Tuo Spirito',
  NewsToKnow: 'Notizie da Sapere',
  TheScoop: 'Uno Spazio',
  CarrierCorner: 'Angolo del Corriere',
  FAQs: 'Fatti',
  Warehouse: 'Magazzino',
  Announcements: 'Annunci',
  Celebrations: 'Celebrazioni',
  AssociateResorce: 'Risorse Associate',
  BRIAnnouncements: 'BRI Annunci',
  SafetyChannel: 'Canale di Sicurezza',
  TheHumanSpirit: 'Lo Spirito Umano',
  PoliciesAndProcedures: 'Politiche e Procedure',
  PromotionsAndRollesChanges: 'Promozioni e Cambi Rolles',
  WelcomeNewHires: 'Benvenuto ai Nuovi Assunti',
  Deparment: 'Dipartimento',
  FirstShiftFreezer: 'Primo Turno Congelatore',
  FirstShiftPerishable: 'Primo Turno Deperibile',
  SecondShiftFreezer: 'Secondo Turno Congelatore',
  SecondShiftPrerishable: 'Secondo Turno Deperibile',
  Sanitation: 'Servizi Igienico-Sanitari'
};

export const French = {
  language: 'French',
  home: 'Début',
  schedule: 'Calendrier',
  channels: 'Canaux',
  notifications: 'Avis',
  more: 'Suite',
  manageShift: 'Gérer les Quarts de Travail',
  firstContact: 'Premier Contact',
  firstContactMsg: 'Nous voulons vous entendre !!',
  suggestionBox: 'Boîte á Auggestion',
  mantSuggestionBox: 'Boîte à Suggestions D\'entretien',
  survey: 'Enquête',
  nextShift: 'Prochaine Équipe !!!',
  personalInformation: 'Informations Personnelles',
  myBenefits: 'Mes Avantages',
  trainingCenter: 'Centre d\'entraînement',
  badges: 'Insignes',
  changeLanguage: 'Changer de Langue',
  humanResources: 'Ressources Humaines',
  diversityAndInclusion: 'Diversité et Inclusion',
  COVID19Comunications: 'COVIT-19 Communication',
  FocusOnWellness: 'Focus sur le Bien-Être',
  StayingSafeAtHome: 'Rester en Sécurité à la Maison',
  FeedYourSpirit: 'Nourrissez Votre Esprit',
  NewsToKnow: 'Nouvelles à Savoir',
  TheScoop: 'Un Espace',
  CarrierCorner: 'Coin Porteur',
  FAQs: 'Faits',
  Warehouse: 'Entrepôt',
  Announcements: 'Annonces',
  Celebrations: 'Célébrations',
  AssociateResorce: 'Ressource Associée',
  BRIAnnouncements: 'BRI Annonces',
  SafetyChannel: 'Canal de Sécurité',
  TheHumanSpirit: 'L\'Esprit Humain',
  PoliciesAndProcedures: 'Les Politiques et les Procédures',
  PromotionsAndRollesChanges: 'Promotions et Changements de Rolles',
  WelcomeNewHires: 'Bienvenue aux Nouvelles Recrues',
  Deparment: 'Département',
  FirstShiftFreezer: 'Congélateur de Première Êquipe',
  FirstShiftPerishable: 'Première Êquipe Périssable',
  SecondShiftFreezer: 'Congélateur de Deuxième Quart de Travail',
  SecondShiftPrerishable: 'Deuxième Quart de Travail',
  Sanitation: 'Assainissement'
};

export const Chinise = {
  language: 'Chinise',
  home: '家',
  schedule: '日程',
  channels: '频道',
  notifications: '通知',
  more: '更多的',
  manageShift: '管理轮班',
  firstContact: '第一次接触',
  firstContactMsg: '我们想听你说！！',
  suggestionBox: '建议箱',
  mantSuggestionBox: '维修意见箱',
  survey: '民意调查',
  nextShift: '下一班！！！',
  personalInformation: '个人信息',
  myBenefits: '我的好处',
  trainingCenter: '培训中心',
  badges: '徽章',
  changeLanguage: '改变语言',
  humanResources: '人力资源',
  diversityAndInclusion: '多元化和包容性',
  COVID19Comunications: 'COVIT-19 通讯',
  FocusOnWellness: '专注于健康',
  StayingSafeAtHome: '居家安全',
  FeedYourSpirit: '喂养你的精神',
  NewsToKnow: '新闻要知道',
  TheScoop: '空间',
  CarrierCorner: '载波角',
  FAQs: '事实',
  Warehouse: '仓库',
  Announcements: '公告',
  Celebrations: '庆祝活动',
  AssociateResorce: '合作资源',
  BRIAnnouncements: '公告',
  SafetyChannel: '安全通道',
  TheHumanSpirit: '人类精神',
  PoliciesAndProcedures: '',
  PromotionsAndRollesChanges: '政策与程序',
  WelcomeNewHires: '欢迎新员工',
  Deparment: '部',
  FirstShiftFreezer: '第一班冷冻室',
  FirstShiftPerishable: '第一班易腐烂',
  SecondShiftFreezer: '二班冷冻室',
  SecondShiftPrerishable: '二班可取',
  Sanitation: '卫生x'
};

export const Russian = {
  language: 'Russian',
  home: 'дом',
  schedule: 'Расписание',
  channels: 'каналы',
  notifications: 'Уведомления',
  more: 'Более',
  manageShift: 'Управление сменами',
  firstContact: 'Первый контакт',
  firstContactMsg: 'Мы хотим вас слышать!!',
  suggestionBox: 'Коробка предложений',
  mantSuggestionBox: 'Коробка с предложениями по техническому обслуживанию',
  survey: 'Опрос',
  nextShift: 'Следующая смена !!!',
  personalInformation: 'Персональные данные',
  myBenefits: 'Мои преимущества',
  trainingCenter: 'Учебный центр',
  badges: 'Значки',
  changeLanguage: 'Изменить язык',
  humanResources: 'Человеческие ресурсы',
  diversityAndInclusion: 'Разнообразие и инклюзивность',
  COVID19Comunications: 'COVIT-19 Связь',
  FocusOnWellness: 'Сосредоточьтесь на благополучии',
  StayingSafeAtHome: 'Безопасность дома',
  FeedYourSpirit: 'Накорми свой дух',
  NewsToKnow: 'Новости, которые нужно знать',
  TheScoop: 'пространство',
  CarrierCorner: 'Несущий уголок',
  FAQs: 'Факты',
  Warehouse: 'Склад',
  Announcements: 'Анонсы',
  Celebrations: 'Торжества',
  AssociateResorce: 'Ассоциированный развод',
  BRIAnnouncements: 'BRI Анонсы',
  SafetyChannel: 'Канал безопасности',
  TheHumanSpirit: 'Человеческий дух',
  PoliciesAndProcedures: 'Политики и процедуры',
  PromotionsAndRollesChanges: 'Акции и изменения в роликах',
  WelcomeNewHires: 'Приветствуем новых сотрудников',
  Deparment: 'отделение',
  FirstShiftFreezer: 'Морозильная камера первой смены',
  FirstShiftPerishable: 'Скоропортящиеся в первую смену',
  SecondShiftFreezer: 'Готовность ко второй смене',
  SecondShiftPrerishable: 'Готовность ко второй смене',
  Sanitation: 'Санитария'
};

export const Portuguese = {
  language: 'Portuguese',
  home: 'Casa',
  schedule: 'Cronograma',
  channels: 'Canais',
  notifications: 'Notificações',
  more: 'Mais',
  manageShift: 'Gerenciar Turnos',
  firstContact: 'Primeiro Contato',
  firstContactMsg: 'Queremos ouvir voce!!',
  suggestionBox: 'Caixa de Sugestões',
  mantSuggestionBox: 'Caixa de Sugestões de Manutenção',
  survey: 'Enquete',
  nextShift: 'Próximo Turno !!!',
  personalInformation: 'Informações Pessoais',
  myBenefits: 'Meus Benefícios',
  trainingCenter: 'Centro de Treinamento',
  badges: 'Distintivos',
  changeLanguage: 'Mudar Idioma',
  humanResources: 'Recursos Humanos',
  diversityAndInclusion: 'Diversidade e Inclusão',
  COVID19Comunications: 'COVIT-19 Comunicações',
  FocusOnWellness: 'Foco no Bem-Estar',
  StayingSafeAtHome: 'Manter a Segurança em Casa',
  FeedYourSpirit: 'Alimente Seu Espírito',
  NewsToKnow: 'Novidades para Saber',
  TheScoop: 'Um Espaço',
  CarrierCorner: 'Carrier Corner',
  FAQs: 'Fatos',
  Warehouse: 'Armazém',
  Announcements: 'Anúncios',
  Celebrations: 'Celebrações',
  AssociateResorce: 'Resorce Associado',
  BRIAnnouncements: 'BRI Anúncios',
  SafetyChannel: 'Canal de Segurança',
  TheHumanSpirit: 'O Espírito Humano',
  PoliciesAndProcedures: 'Políticas e Procedimentos',
  PromotionsAndRollesChanges: 'Promoções e Mudanças nos Rolles',
  WelcomeNewHires: 'Bem-vindos, Novos Contratados',
  Deparment: 'Departamentos',
  FirstShiftFreezer: 'Congelador de Primeiro Turno',
  FirstShiftPerishable: 'Perecível no Primeiro Turno',
  SecondShiftFreezer: 'Congelador de Segundo Turno',
  SecondShiftPrerishable: 'Pré-perecível de Segundo Turno',
  Sanitation: 'Saneamento'
};

export const Arabic = {
  language: 'Arabic',
  home: 'الرئيسية',
  schedule: 'جدول',
  channels: 'القنوات',
  notifications: 'إشعارات',
  more: 'أكثر',
  manageShift: 'إدارة الورديات',
  firstContact: 'الاتصال الاول',
  firstContactMsg: 'نريد أن نسمعك',
  suggestionBox: 'صندوق الاقتراحات',
  mantSuggestionBox: 'صندوق اقتراحات الصيانة',
  survey: 'الدراسة الاستقصائية',
  nextShift: 'التحول القادم',
  personalInformation: 'معلومات شخصية',
  myBenefits: 'مزاياي',
  trainingCenter: 'مركز تدريب',
  badges: 'شارات',
  changeLanguage: 'تغيير اللغة',
  humanResources: 'الموارد البشرية',
  diversityAndInclusion: 'التنوع والتضمين',
  COVID19Comunications: 'COVIT-19 مجال الاتصالات',
  FocusOnWellness: 'ركز على العافية',
  StayingSafeAtHome: 'البقاء في أمان في المنزل',
  FeedYourSpirit: 'غذي روحك',
  NewsToKnow: 'أخبار يجب معرفتها',
  TheScoop: 'مساحة',
  CarrierCorner: 'ركن الناقل',
  FAQs: 'حقائق',
  Warehouse: 'مستودع',
  Announcements: 'الإعلانات',
  Celebrations: 'احتفالات',
  AssociateResorce: 'مساعد',
  BRIAnnouncements: 'الإعلانات',
  SafetyChannel: 'قناة الأمان',
  TheHumanSpirit: 'الروح البشرية',
  PoliciesAndProcedures: 'السياسات والإجراءات',
  PromotionsAndRollesChanges: 'السياسات والإجراءات',
  WelcomeNewHires: 'نرحب بالتعيينات الجديدة',
  Deparment: 'قسم، أقسام',
  FirstShiftFreezer: 'فريزر التحول الأول',
  FirstShiftPerishable: 'التحول الأول قابل للتلف',
  SecondShiftFreezer: 'فريزر التحول الثاني',
  SecondShiftPrerishable: 'التحول الثاني قابل للتلف',
  Sanitation: 'الصرف الصحي'
};

